export const terminalLayerAreEqual = (
  prev: Record<string, unknown>,
  next: Record<string, unknown>,
): boolean => (
  prev.hosts === next.hosts &&
  prev.customGroups === next.customGroups &&
  prev.groupConfigs === next.groupConfigs &&
  prev.proxyProfiles === next.proxyProfiles &&
  prev.keys === next.keys &&
  prev.snippets === next.snippets &&
  prev.snippetPackages === next.snippetPackages &&
  prev.notes === next.notes &&
  prev.noteGroups === next.noteGroups &&
  prev.openNoteRequest === next.openNoteRequest &&
  prev.onOpenVaultNoteFromChat === next.onOpenVaultNoteFromChat &&
  prev.onOpenVaultHostFromChat === next.onOpenVaultHostFromChat &&
  prev.onOpenVaultSectionFromChat === next.onOpenVaultSectionFromChat &&
  prev.sessions === next.sessions &&
  prev.workspaces === next.workspaces &&
  prev.knownHosts === next.knownHosts &&
  prev.draggingSessionId === next.draggingSessionId &&
  prev.terminalTheme === next.terminalTheme &&
  prev.terminalThemeId === next.terminalThemeId &&
  prev.followAppTerminalTheme === next.followAppTerminalTheme &&
  prev.pickTerminalTheme === next.pickTerminalTheme &&
  prev.resolveSessionAppearance === next.resolveSessionAppearance &&
  prev.accentMode === next.accentMode &&
  prev.customAccent === next.customAccent &&
  prev.terminalSettings === next.terminalSettings &&
  prev.fontSize === next.fontSize &&
  prev.hotkeyScheme === next.hotkeyScheme &&
  prev.disableTerminalFontZoom === next.disableTerminalFontZoom &&
  prev.restoreTerminalCwd === next.restoreTerminalCwd &&
  prev.keyBindings === next.keyBindings &&
  prev.sftpDefaultViewMode === next.sftpDefaultViewMode &&
  prev.sftpDoubleClickBehavior === next.sftpDoubleClickBehavior &&
  prev.sftpAutoSync === next.sftpAutoSync &&
  prev.sftpShowHiddenFiles === next.sftpShowHiddenFiles &&
  prev.sftpUseCompressedUpload === next.sftpUseCompressedUpload &&
  prev.sftpAutoOpenSidebar === next.sftpAutoOpenSidebar &&
  prev.sftpFollowTerminalCwd === next.sftpFollowTerminalCwd &&
  prev.setSftpFollowTerminalCwd === next.setSftpFollowTerminalCwd &&
  prev.editorWordWrap === next.editorWordWrap &&
  prev.sshDebugLogsEnabled === next.sshDebugLogsEnabled &&
  prev.showHostTreeSidebar === next.showHostTreeSidebar &&
  prev.setEditorWordWrap === next.setEditorWordWrap &&
  prev.onHotkeyAction === next.onHotkeyAction &&
  prev.onUpdateSessionRestoreCwd === next.onUpdateSessionRestoreCwd &&
  prev.onUpdateHost === next.onUpdateHost &&
  prev.onAddKnownHost === next.onAddKnownHost &&
  prev.onToggleWorkspaceViewMode === next.onToggleWorkspaceViewMode &&
  prev.onSetWorkspaceFocusedSession === next.onSetWorkspaceFocusedSession &&
  prev.onReorderWorkspaceSessions === next.onReorderWorkspaceSessions &&
  prev.onReorderTabs === next.onReorderTabs &&
  prev.onSplitSession === next.onSplitSession &&
  prev.onConnectToHost === next.onConnectToHost &&
  prev.onCreateLocalTerminal === next.onCreateLocalTerminal &&
  prev.isBroadcastEnabled === next.isBroadcastEnabled &&
  prev.onToggleBroadcast === next.onToggleBroadcast &&
  prev.updateSnippets === next.updateSnippets &&
  prev.updateSnippetPackages === next.updateSnippetPackages &&
  prev.updateNotes === next.updateNotes &&
  prev.updateNoteGroups === next.updateNoteGroups &&
  prev.toggleScriptsSidePanelRef === next.toggleScriptsSidePanelRef &&
  prev.toggleSidePanelRef === next.toggleSidePanelRef &&
  prev.identities === next.identities &&
  prev.shellHistory === next.shellHistory
);
